name: Replace Old URLs with New URLs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  replace-urls:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Find and Replace Old URLs
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "https://mazen-ghzaly.github.io/home"
          replace: "https://mazen-ghzaly.github.io/"
          regex: false

      - name: Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Auto-replace old URLs with new base URL"
          file_pattern: ":(exclude).github/workflows/*"
